// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.g.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsLbrEohcJznQ4g1PoCvuXbfVb00VALu8',
    appId: '1:608707985703:web:53ace9892f38c375622902',
    messagingSenderId: '608707985703',
    projectId: 'quizly-market-app',
    authDomain: 'quizly-market-app.firebaseapp.com',
    storageBucket: 'quizly-market-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATFbwhcHSE8sN418BlHDLBOkKGz5ZGpbI',
    appId: '1:608707985703:android:5aa290f2c0915101622902',
    messagingSenderId: '608707985703',
    projectId: 'quizly-market-app',
    storageBucket: 'quizly-market-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGwMAdXI9Z6ws8l_FxJHHCBnb6Xf71zAE',
    appId: '1:608707985703:ios:7425336c5ccb8015622902',
    messagingSenderId: '608707985703',
    projectId: 'quizly-market-app',
    storageBucket: 'quizly-market-app.firebasestorage.app',
    iosBundleId: 'com.quizly.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGwMAdXI9Z6ws8l_FxJHHCBnb6Xf71zAE',
    appId: '1:608707985703:ios:7425336c5ccb8015622902',
    messagingSenderId: '608707985703',
    projectId: 'quizly-market-app',
    storageBucket: 'quizly-market-app.firebasestorage.app',
    iosBundleId: 'com.quizly.app',
  );
}
