// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3GZV1tAc8xPTUERhUEcgwYBs5wWcCb1M',
    appId: '1:568369386495:web:a9943580beaebbfa1e4dca',
    messagingSenderId: '568369386495',
    projectId: 'test-9cf8b',
    authDomain: 'test-9cf8b.firebaseapp.com',
    storageBucket: 'test-9cf8b.firebasestorage.app',
    measurementId: 'G-EVNGZGHBE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWiCeNXuZh7skW7F9-pWWTt2TABs15IwQ',
    appId: '1:568369386495:android:dcf3206f6a31f9431e4dca',
    messagingSenderId: '568369386495',
    projectId: 'test-9cf8b',
    storageBucket: 'test-9cf8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3j_HAwq0dyBi8KnCgPNUeUi7l85tYoOY',
    appId: '1:568369386495:ios:9b83ac266c2e015e1e4dca',
    messagingSenderId: '568369386495',
    projectId: 'test-9cf8b',
    storageBucket: 'test-9cf8b.firebasestorage.app',
    iosBundleId: 'com.quizly.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3j_HAwq0dyBi8KnCgPNUeUi7l85tYoOY',
    appId: '1:568369386495:ios:acc99e27da3ad29c1e4dca',
    messagingSenderId: '568369386495',
    projectId: 'test-9cf8b',
    storageBucket: 'test-9cf8b.firebasestorage.app',
    androidClientId: '568369386495-umvco3b8jgp3l3bvdrmh7aj6q35drjsh.apps.googleusercontent.com',
    iosClientId: '568369386495-17m34mrumh2njfsov3mbu51i2k2gna84.apps.googleusercontent.com',
    iosBundleId: 'com.flutterbro.quizlyMarket',
  );
}
